### ISSUE TITLE
Updating test file.

### ISSUE THREAD

**Issue by orelbn** [Shopify/eng-intern-assessment-react#22]
Hi, I needed to update the test files and package.json to get the tests to run for me. 

Are we okay to modify those files?

For package.json I installed  ```"jest-environment-jsdom": "^29.7.0"``` and  ```"@testing-library/jest-dom": "^6.2.0"```.
I set the test environment to jsdom 
```
"jest": {
    "testEnvironment": "jsdom",
    "transform": {
      "^.+\\.(js|jsx|ts|tsx)$": "babel-jest"
    }
```

In stopWatch.test.js I imported
```import "@testing-library/jest-dom"; ```

Otherwise, I get an error:
![image](https://github.com/Shopify/eng-intern-assessment-react/assets/77707952/e82dd585-59d1-4383-b4df-6938e8118424)

**Comment by jasonntruong** [comment]
+1

**Comment by samzhao273** [comment]
> I also noticed that there's `pause` and `resume` button selectors in this following test:
> 
> ```js
>   test('pauses and resumes the stopwatch', () => {
>     render(<Stopwatch />);
>     
>     fireEvent.click(screen.getByText('Start'));
>     fireEvent.click(screen.getByText('Pause'));
>     const pausedTime = screen.getByText(/(\d{2}:){2}\d{2}/).textContent;
> 
>     fireEvent.click(screen.getByText('Resume'));
>     expect(screen.getByText(/(\d{2}:){2}\d{2}/).textContent).not.toBe(pausedTime);
>   });
> ```
> 
> But there's no mention of these button's in the README. Is this intentional, or they be `stop` and `start`?

+1
